#include <stm32f4xx_hal.h> // Platformio automatically sets the include to add the path where the stm32f4 HAL lib is.
#include <stdio.h>

#include "usart.h"
#include "i2c.h"
#include "si7021.h"

int main(void)
{
	/* Call autogenerated functions from STM32Cube.
	With STM32 Cube you can configure in a graphical interface the I2C1 and USART2.
	Then STM32 Cube will generate for you some C code that configures those
	peripherals.
	See https://www.digikey.com/en/maker/projects/getting-started-with-stm32-i2c-example/ba8c2bfef2024654b5dd10012425fa23?_ga=2.178792940.914495656.1666604063-451975193.1666604063
	We are using other board, but the procedure is very similar. */

	HAL_Init(); /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
	MX_I2C1_Init(); /* Configure I2C1 as it is the one we will be using.*/
	MX_USART2_UART_Init(); /* Configure the USART2 just for printing.*/


	char usart_buf[50];

	while (1)
	{
		// Start humidity measurement
		uint32_t humidity = si7021_measure_humidity(&hi2c1);
		if (humidity == SI7021_MEASURE_FAILED) {
			// Error happened :(
			sprintf(usart_buf, "Error");
		}

		else
		{
			/* As a side effect si7021 measures temperate together with humidity
			   so you can just read it without additional measurement */
			int32_t tempC = si7021_read_previous_temperature(&hi2c1);

			/* This print is just for demo purposes. Do not use in real code.
			   For example the %d are wrong as the values are in 32 bits */
			sprintf(usart_buf, "Humidity: %d Temperature: %d", humidity, tempC);
		}

		send_string_usart2(usart_buf);

		HAL_Delay(2000);
	}
}


/**
  * @brief Required to use HAL_Delay
  * @param None
  * @retval None
  */
void SysTick_Handler(void)
{
  HAL_IncTick();
}